Support JSON API access with personal OAuth tokens
hitobito/hitobito pull request #1115
Opened 2020-12-27 13:33 UTC by MartinGantenbein

Bezieht sich auf #1040 

Damit können die JSON-APIs mit den Berechtigungen eines Users aufgerufen werden, statt mit einem "persönlichen Token" aber mit OAuth-Token. Das heisst:
* Die Drittapplikation nutzt Hitobito OAuth als Authentication Provider und erhält somit keinen Zugriff auf User-Credentials
* Der Administrator muss für die Drittapplikation OAuth mit Scope "api" einrichten
* Der User muss der Drittapplikation erlauben, in seinem Namen auf die JSON-APIs zuzugreifen
* Der User muss kein persönliches Token erstellen und verwalten
* Drittapplikation erhält nur für beschränkte Zeit Zugang (im Gegensatz zu den "persönlichen Tokens")
* Drittapplikation erhält nur die Berechtigungen des angemeldeten Users (im Gegensatz zu den Service-Tokens)

2021-01-07 09:40 UTC, TheWalkingLeek commented
Hoi Martin, merci für deinen PR, wir nehmen das gerne auf!
Denkst du aber es ist nötig das factory_bot_rails gem neu aufzunehmen? Kann man diese Specs nicht auch mit Fabricate oder anderen Tools welche wir schon verwenden umsetzen?

2021-01-09 08:26 UTC, MartinGantenbein commented
Hoi @TheWalkingLeek, danke für den Hint, ich habe die Specs auf Fabricate umgestellt.

2021-01-12 10:32 UTC, psunix requested changes
vielen Dank @MartinGantenbein für diesen PR!
ich habe noch ein paar Inputs vermerkt.

2021-01-12 10:32 UTC, psunix commented on spec/requests/groups.spec
> +# encoding: utf-8
bisher haben wir ja noch keine request specs und ich denke es ist ok wenn wir hier diesen folder neu anlegen.

die file extension .spec ist aber neu für mich. werden die specs so ausgeführt ?

groups_spec.rb ?

2021-01-13 20:17 UTC, carlobeltrame approved these changes
Danke vielmals für diesen PR! Sehr gute Arbeit!

Ich habe das Ganze noch funktional durchgetestet, klappt alles wie erwartet.
Ich habe noch die Dokumentation leicht ergänzt, und ausserdem die Erklärung für die Benutzer etwas ausgeführt, sodass man auf dem Confirmation Dialog die Auswirkungen dieses neuen Scopes genauer abschätzen kann.

Der nächste Schritt der jetzt noch fehlt ist CORS für die API. Das sollte im Fall von OAuth Tokens machbar sein, jedenfalls einfacher als bei den personal Access Tokens und Service Tokens.

2021-01-14 09:15 UTC, merged