Add message and related models
hitobito/hitobito pull request #1126
Opened 2021-01-11 13:36 UTC by amaierhofer

Modell für Messages und Dispatches. 

- `message` ist ein STI Model und erlaubt verschiedene Ausprägungen (SMS, Brief, BriefMitRechnung) 
- `message_dispatch` wird angelegt, wenn die Nachricht verschickt oder als Druckauftrag freigegeben wird
- `message_reciept` wird angelegt, wenn die Nachricht einer Person zugestellt/zugeordnet wird. Somit kann auf der Person einen Liste der Empfangen Nachrichten angezeigt werden. 

refs hitobito/hitobito_cvp#84

2021-01-11 13:41 UTC, psunix commented
zu message_reciept:

- eine Person kann mehrere Mailadressen haben
- die Mail Adresse kann ändern
- die MailingListe kann gelöscht werden

müsste man diese info beim Senden irgendwo cachen? 
nur soft delete für mailinglisten ?

2021-01-11 13:57 UTC, amaierhofer commented
`MailingList` soft delete würde ich jetzt nicht machen, eventuell später. Fürs erste denke ich ist es ausreichend, wenn die  `Message` erhalten bleibt, dies ist gesichert durch `restrict_with_error` falls dafür ein `MessageDispatch` existiert.  

Ich denk wir werden die `Message` in der Regel nur einmal an die Person zustellen. Mit dem bestehenden Modell wäre es allerdings auch möglich eine Message mehrmals an eine Person auszuliefern. 

Ich hab mir auch überlegt, ob wir die Kontaktdaten (Address, Email Address) auf die reciept nehmen sollte, habe letzten  aber keine Grund dafür gefunden.

2021-01-12 07:08 UTC, psunix commented
> h hab mir auch überlegt, ob wir die Kontaktdaten (Address, Email Address) auf die reciept nehmen sollte, habe letzten aber keine Grund dafür gefunden.

ja die E-Mail, Telefonnr. oder Adresse einer Person kann ändern. Ich denke es macht sinn das wir diesen Wert auf dem Message Recipient hinterlegen.

2021-01-12 07:19 UTC, psunix commented on app/models/message.rb
> +#  https://github.com/hitobito/hitobito_cvp.
ist nicht teil von hitobito_cvp sondern hitobito core

2021-01-12 07:19 UTC, psunix commented on app/models/message.rb
> +#  recipient_count    :integer          default(0)
sollte man dieses attribute nicht besser auf das dispatch model verschieben ?

2021-01-12 07:19 UTC, psunix commented on app/models/message.rb
> +#  invoice_attributes :text(65535)
eigenes model für die ganze Invoice Mapping Geschichte ?

2021-01-12 07:19 UTC, psunix commented on app/models/message_reciept.rb
> +# == Schema Information
braucht es auf diesem model noch ein status ?

:sent, :failed ?

2021-01-12 07:19 UTC, psunix commented on app/models/message.rb
> +#  source_id          :bigint
recipient_source finde ich sprechender

2021-01-12 07:19 UTC, psunix commented on app/models/message_dispatch.rb
> +#  channel       :string(255)      default("print"), not null
braucht es diese info ? das findet man ja eigentlich über den message type raus, nicht ?

2021-01-12 07:22 UTC, psunix commented
fehlt nicht noch ein Message Status ?

sowas wie Gesendet, Entwurf, In Bearbeitung, wird Versendet

MailLog hat heute auch diverse Stati ... macht wohl Sinn das wir diese entsprechend z.B. auf das MessageDispatch verschieben.

2021-01-12 07:23 UTC, psunix commented
Grundsätzlich finde ich den Ansatz mit `message`, `message_dispatch`, `message_receipt` sehr gut ! :dancers: :partying_face:

2021-01-12 16:24 UTC, amaierhofer commented on app/models/message.rb
> +#  invoice_attributes :text(65535)
Habs rausgenommen, können wir nochmal überlegen aber das hier wäre sicher der einfachste weg.

2021-01-12 16:24 UTC, amaierhofer commented on app/models/message_dispatch.rb
> +#  channel       :string(255)      default("print"), not null
Habe ich entfernt

2021-01-12 16:27 UTC, amaierhofer commented
Hab die meisten der besprochenen Änderungen übernommen, die anderen branches setzten auf dieses Modell auf. Wenn die anderen branches auf Funktionalität getestet wurden sind denke ich können wir langsam darüber nachdenke das zu mergen

2021-01-12 16:28 UTC, amaierhofer commented on app/models/message_reciept.rb
> +# == Schema Information
Habe eine `state` Spalte hinzugefügt (analog `invoices`)

2021-01-13 08:29 UTC, psunix requested changes
sieht soweit gut aus.

source würde ich definitiv immer noch in recipients_source renamen.
reciept in recipients

2021-01-13 08:29 UTC, psunix commented on app/models/message.rb
> +#  source_id   :bigint
ich würde hier recipient_source immer noch bevorzugen.
wenn ich an message source denke dann ist das für mich z.B. bei einem mail eher der source des mails und ich würde nie auf die empfänger kommen.

2021-01-13 08:29 UTC, psunix commented on app/models/message.rb
> +  has_many :message_reciepts, through: :message_dispatch
reciepts ist kein englisches wort. 
receipt? meinst du damit eine Art Quittung ?
ich würde recipients verwenden. -> Empfänger

2021-01-13 08:29 UTC, psunix commented on app/models/message_reciept.rb
> +#  person_id           :bigint           not null
das mit dem cachen der empfänger adresse/nr lassen wir weg ?

2021-01-13 08:29 UTC, psunix commented on spec/models/mailing_list_spec.rb
> +  context 'messages' do
hmm ... wie wäre es damit das mailing listen gar nicht mehr gelöscht werden können sobald nachrichten vorhanden sind ? ich finde das würde einige probleme lösen :)

2021-01-13 13:26 UTC, closed without merging