Feature/cvp 26 assignments
hitobito/hitobito pull request #1145
Opened 2021-02-01 07:59 UTC by TheWalkingLeek

Fixes https://github.com/hitobito/hitobito_cvp/issues/26

2021-02-01 15:23 UTC, psunix requested changes
sieht schon sehr gut aus :dancers: 

- bei den aufträgen / person index wird ein new button angezeigt? den brauchts noch nicht, oder?

2021-02-04 08:59 UTC, TheWalkingLeek commented on app/jobs/assignment/send_notification_job.rb
> +    super()
Das wird hier benötigt. Da Ruby bei `super` auch dieselben parameter automatisch mitgegeben werden. In diesem fall wäre dass dann dasselbe wie `super(assignment)`

2021-02-04 14:28 UTC, psunix requested changes
nice! schon ein grosses Feature mit 768 Zeilen!
zwei Inputs:
- ich denke das mit der Index Ability musst du noch prüfen
- Anstatt owner oder recipient: was hälst du vom Begriff assignee? ich habe diesen Begriff schon sehr oft gelesen und finde ihn auch hier viel passender.

2021-02-04 14:28 UTC, psunix commented on app/abilities/message_ability.rb
> +    subject.assignments.any? { |a| [a.person_id, a.creator_id].include?(user.id) }
:+1:

2021-02-04 14:28 UTC, psunix commented on app/controllers/assignments_controller.rb
> +  before_action :set_read_at, only: :show, if: :assignment_owner?
nice! wird sogar geprüft ob owner !

2021-02-04 14:28 UTC, psunix commented on app/controllers/assignments_controller.rb
> +    ActiveRecord::Base.transaction do
can't u use super here?

or even use callbacks for notify ? https://github.com/codez/dry_crud#crud-controller-callbacks-

2021-02-04 14:28 UTC, psunix commented on app/controllers/assignments_controller.rb
> +    entry.person = default_recipient
default_assignee ?

2021-02-04 14:28 UTC, psunix commented on app/controllers/assignments_controller.rb
> +  def assignment_owner?
assignee?

2021-02-04 14:28 UTC, psunix commented on app/controllers/assignments_controller.rb
> +    entry.update!(read_at: DateTime.now) unless entry.read_at
Time.zone.now ? glaube man sollte immer das brauchen

2021-02-04 14:28 UTC, psunix commented on app/controllers/messages/dispatches_controller.rb
> +        new_assignment_path(assignment: { attachment_id: message.id, attachment_type: 'Message'},
Message.sti_name

2021-02-04 14:28 UTC, psunix commented on app/jobs/assignment/send_notification_job.rb
> +  def recipient_email
assignee

2021-02-04 14:28 UTC, psunix commented on spec/controllers/assignments_controller_spec.rb
> +    it 'does not updates read_at if not assignment owner' do
```suggestion
    it 'does not update read_at if not assignee' do
```

2021-02-08 12:02 UTC, psunix commented on config/routes.rb
> +        resources :assignments, only: [:show, :edit, :update]
gibt es einen grund diese nicht auch unter person zu nesten? bei show, edit und update ist ja die id der person bekannt.

2021-02-08 12:07 UTC, psunix commented on db/migrate/20210122101242_create_assignments.rb
> +class CreateAssignments < ActiveRecord::Migration[6.0]
license header and frozen ....  :cold_face:

2021-02-08 12:10 UTC, psunix approved these changes
wonderful :partying_face:

2021-02-08 14:18 UTC, merged