Implement text messages, refs hitobito/hitobito_cvp#34
hitobito/hitobito pull request #1148
Opened 2021-02-03 08:14 UTC by psunix

2021-02-03 11:22 UTC, psunix commented
`USE eager loading detected Message::TextMessage => [:group] Add to your query: .includes([:group])`
zeigt es mir bei index an. verstehe nicht warum?!

2021-02-03 11:33 UTC, psunix commented
![image](https://user-images.githubusercontent.com/655627/106741467-05f51f80-661c-11eb-84e1-1f8ed4ffe77e.png)

auf der Gruppe des Abos bei den Einstellungen den Provider hinzufügen.

2021-02-04 10:00 UTC, carlobeltrame requested changes

2021-02-08 08:23 UTC, psunix commented on app/controllers/invoices_controller.rb
> -                            :id,
gute frage! vermutlich reingerutscht

2021-02-08 08:25 UTC, psunix commented on app/controllers/messages_controller.rb
> +                                    ]}]
freeze baby

2021-02-08 08:30 UTC, psunix commented on app/domain/messages/text_message_dispatch.rb
> +        sleep 15 unless Rails.env.test? # give it some time to deliver messages
hmm ... habe mal ein ticket erstellt: https://github.com/hitobito/hitobito_cvp/issues/110

2021-02-08 09:17 UTC, psunix commented on app/domain/messages/text_message_dispatch.rb
> +      if send_text_message
:exclamation:

2021-02-08 09:19 UTC, psunix commented on app/domain/messages/text_message_dispatch.rb
> +      recipient.update!(state: state || 'failed', error: error)
ich finde es ohne early return leserlicher und elegant von dem her das recipient.update! nur einmal besteht

2021-02-08 09:20 UTC, psunix commented on app/domain/messages/text_message_provider/aspsms.rb
> +        status_value.eql?('0') ? :ok : :error
delivery status ist eben wieder anderst habe ich festgestellt. Ist aber schlecht dokumentiert bei aspsms.

2021-02-08 09:31 UTC, psunix commented on app/domain/messages/text_message_provider/aspsms.rb
> +        params[:MessageText] = text[0..MAX_CHARS - 1]
umlaute gehen bei mir wunderbar. wie kommst du darauf das das nicht geht?

2021-02-08 09:32 UTC, psunix commented on app/domain/messages/text_message_provider/aspsms.rb
> +        params[:MessageText] = text[0..MAX_CHARS - 1]
![aspsms](https://user-images.githubusercontent.com/655627/107201208-fb120480-69f8-11eb-9c40-cd12469ebf87.jpeg)

2021-02-08 09:34 UTC, psunix commented on app/domain/messages/text_message_provider/base.rb
> +          raise 'unkown text message provider in config'
hmmm ... nein man kann irgend einen wert eingeben. ich schaue mal was ich machen kann um das einzuschränken

2021-02-08 09:39 UTC, psunix commented on app/domain/messages/text_message_provider/base.rb
> +          raise 'unkown text message provider in config'
https://github.com/hitobito/hitobito_cvp/issues/114
habe ein ticket gemacht

2021-02-08 09:40 UTC, psunix commented on app/domain/messages/text_message_dispatch.rb
> +    delegate :update, :success_count, to: '@message'
wurde im letter dispatch auch schon so gemacht. ich lasse es mal so.

2021-02-08 09:43 UTC, psunix commented on app/views/messages/_actions_show.html.haml
> +  = action_button(t('.button_dispatch_text_message'), message_dispatch_path(message_id: entry.id), :paper_plane, method: :post)
nein, braucht es das? 
dispatch ist so gemacht das eine message nur 1 mal versendet wird.

2021-02-08 11:42 UTC, merged