Feature/bbt 09 upgrade faker gem
hitobito/hitobito pull request #1159
Opened 2021-02-16 13:36 UTC by miosidler

Updated faker gem

2021-02-18 12:25 UTC, olibrian commented
Issue: https://github.com/hitobito/hitobito/issues/1132

2021-02-22 13:10 UTC, miosidler commented
Seeding works on both the hitobito generic and jubla instance. Wagon-specific testing runs clean on generic instance, still pending on jubla instance.

2021-02-23 06:36 UTC, psunix requested changes
@miosidler merci für den PR. es gibt noch ein paar tests im core die failen die du noch fixen musst: z.B. /spec/migrations/migrate_mail_log_spec.rb

ich habe deine einzelnen commits in einen einzelnen gesquashed. Siehe git squash. ausserdem auf den master rebased (bitte immer machen bevor du einen PR zum reviewen weitergibst)

du kannst rubocop-faker installieren um die faker updates automatisch zu machen.

2021-02-24 07:25 UTC, closed without merging

2021-02-26 13:17 UTC, lucashabersaat commented
Die Wagons **jubla**, **pbs** und **sbv** haben ebenso kleine Fixes bekommen. Die Restlichen Wagons sind ok.

Hier die Pull Requests, die, nachdem der Core gemerged ist, gleich nachgezogen werden sollen:
https://github.com/hitobito/hitobito_jubla/pull/25
https://github.com/hitobito/hitobito_pbs/pull/187
https://github.com/hitobito/hitobito_sbv/pull/93