Adjust permissions and UI for people without roles
hitobito/hitobito pull request #1208
Opened 2021-03-12 08:05 UTC by TheWalkingLeek

Closes #948 
Closes #1203

2021-03-12 08:52 UTC, carlobeltrame commented on app/abilities/person_ability.rb
> +    permission(:any).may(:update_password).if_password_present
Klappt der Link im "Login schicken" E-Mail nach dieser Änderung noch?

2021-03-12 08:52 UTC, carlobeltrame commented on app/controllers/person/log_controller.rb
> +    end
Vielleicht in application_controller oder einen Concern verschieben?

2021-03-12 08:52 UTC, carlobeltrame commented on app/helpers/sheet_helper.rb
> +    # if current_user && current_user.roles.any?
Auskommentierten Code entfernen?

2021-03-12 08:52 UTC, carlobeltrame commented on app/views/layouts/application.html.haml
> +        - if current_user && current_user.roles.present?
Warum brauchts hier zusätzlich einen Check `current_user` und an allen anderen Stellen in dieser Datei nicht? Wäre `current_user?.roles.present?` eine Option?

2021-03-12 08:52 UTC, carlobeltrame commented on app/views/people/_actions_show.html.haml
>    - if entry.encrypted_password?
Jetzt wo du das in einer Ability hast, könntest du diesen Check durch eine CanCan Assertion ersetzen.

2021-03-12 08:52 UTC, carlobeltrame commented on spec/controllers/devise/registrations_controller_spec.rb
> +      before { person.update!(encrypted_password: nil) }
Hier hast du `update!` verwendet, weiter unten `update` (ohne Ausrufezeichen). Vielleicht an beiden Orten gleich machen?

2021-03-12 10:53 UTC, TheWalkingLeek commented on app/abilities/person_ability.rb
> +    permission(:any).may(:update_password).if_password_present
Ja klappt noch. `authorize!` wird nur im Devise::RegistrationsController gemacht. Der Mail Link geht auf Devise::PasswordsController

2021-03-15 17:31 UTC, carlobeltrame requested changes
Ich habs mit dem PBS-Wagon getestet, dort hat der Root User keine Rollen, und somit nun keine Möglichkeit mehr, ernsthaft mit hitobito zu arbeiten. Wir haben ja noch eine Diskussion über einheitliche Logins offen, aber solange die nicht abgeschlossen ist, wäre das ein Rückschritt für den Development Setup. Eine Lösung wäre es, wenn du in den Seeds aller Wagons nachschaust und wo nötig eine Rolle auf dem Dachverband für den Root User (User mit email == Settings.root_email) erstellst. Was denkst du dazu?

2021-03-18 15:02 UTC, merged