Imap client, refs: #1320
hitobito/hitobito pull request #1365
Opened 2021-08-10 07:53 UTC by luca-bruegger

2021-08-10 09:07 UTC, TheWalkingLeek requested changes

2021-08-13 13:21 UTC, carlobeltrame commented on app/utils/imap/mail.rb
> +    (self.mail.text_part || self.mail).body.decoded
All die Aufrufe zu `mail` brauchen kein `self.` oder?

2021-08-13 13:21 UTC, carlobeltrame commented on app/views/mailing_lists/imap_mails/index.html.haml
> +      - t('mailing_lists.imap_mails.headers.states.' + imap_mail_state(m))
Hier könnte man als Default noch den state selber anzeigen:
```suggestion
      - t('mailing_lists.imap_mails.headers.states.' + imap_mail_state(m), default: imap_mail_state(m))
```
Dann wird im Zweifelsfall im UI `some_unknown_state` statt `mailing_lists.imap_mails.headers.states.some_unknown_state` angezeigt.

2021-08-16 21:40 UTC, kronn approved these changes

2021-08-20 12:39 UTC, merged