Add donation domain class and invoice config fields for variable donation amount calculation, refs: die_mitte#173
hitobito/hitobito pull request #1366
Opened 2021-08-10 14:44 UTC by TheWalkingLeek

Closes: https://github.com/hitobito/hitobito_die_mitte/issues/173

2021-08-13 13:07 UTC, carlobeltrame requested changes

2021-08-13 13:07 UTC, carlobeltrame commented on config/locales/models.de.yml
> +        donation_calculation_year_amount: Anzahl Jahre
Wie wäre es mit etwas ähnlichem wie:
> Zahlungen aus den letzten [____________] Jahren berücksichtigen.

Wobei [___________] das Input-Feld ist? Oder allenfalls ein erklärender Satz in `help-inline` oder `help-block` wie bei Schulklasse bzw. Zusätzliche Angaben hier:
![Screenshot from 2021-08-13 15-02-11](https://user-images.githubusercontent.com/7566995/129360975-ff0ce7a8-1204-4e67-aa04-e63ede5caf56.png)

2021-08-13 13:07 UTC, carlobeltrame commented on db/migrate/20210810115706_add_variable_donation_amount_columns_to_invoice_config.rb
> +    add_column :invoice_configs, :donation_calculation_year_amount, :integer
Falls du noch nach Namen suchst, wie wärs mit `donation_year_count`?

2021-08-13 14:25 UTC, TheWalkingLeek commented on app/domain/donation.rb
> +    @donations = @donations.joins(:invoice).where(invoices: { group: layer })
Nope macht nur ein join :)

2021-08-17 21:42 UTC, kronn requested changes
Eine Frage und einen Löschwunsch, ansonsten sieht es gut aus.

2021-08-17 21:42 UTC, kronn commented on app/controllers/invoice_configs_controller.rb
> +                          :due_days,
Warum muss `:due_days` noch erlaubt werden?

2021-08-17 21:42 UTC, kronn commented on spec/fixtures/invoice_configs.yml
> +#
```suggestion
```

2021-08-18 06:14 UTC, TheWalkingLeek commented on app/controllers/invoice_configs_controller.rb
> +                          :due_days,
Die due days haben eigentlich nichts mit dem Feature zu tun. Ist aber ein Feld im Formular und war nicht permitted.
Hab dann keinen Commit gefunden, der das Feld bewusst entfernt, daher hab ichs dann einfach wieder eingeführt 🤔

2021-08-18 09:13 UTC, merged