Enable csv export for messages, refs die_mitte#127
hitobito/hitobito pull request #1375
Opened 2021-08-20 11:18 UTC by TheWalkingLeek

Closes https://github.com/hitobito/hitobito_die_mitte/issues/127

2021-08-23 13:40 UTC, olibrian commented
Habe noch gerade Rückmeldung vom Kunde erhalten. Können wir noch die Person ID mitnehmen? Dies würde viel erleichtern.

2021-08-24 12:31 UTC, carlobeltrame requested changes
Sieht gut aus. Ich sehe aber noch nicht, wo mehrere Personen in demselben Haushalt zusammengefasst werden..? Bisher musste sich die Druckerei noch nicht mit Haushalten / Haushalts-IDs auseinandersetzen. Gibt es hier eine Abmachung mit Stefan dass wir deine technisch einfachere und schönere Lösung umsetzen können?

2021-08-24 18:49 UTC, olibrian commented
Ich habe die Anpassungen betreffend Haushalt Export beim Issue https://github.com/hitobito/hitobito_die_mitte/issues/166 ergänzt. Passt dies so oder sieht du @carlobeltrame noch weiteren Bedarf?

2021-08-25 08:13 UTC, carlobeltrame commented
Ich habs noch nicht manuell durchgetestet, aber wenn Nils das gemacht hat passts für mich.

2021-08-25 09:50 UTC, merged