Implement invitations to events, refs: #1276
hitobito/hitobito pull request #1401
Opened 2021-09-27 09:14 UTC by TheWalkingLeek

2021-09-28 10:35 UTC, kronn requested changes
Ich habe ein paar kleine unwichtige Änderungen. Quasi als Nachweis, dass ich alles angesehen habe. :-)

2021-09-28 10:35 UTC, kronn commented on spec/controllers/event/invitations/decline_controller_spec.rb
> +      expect(invitation.status).to eq :declined
```suggestion
      expect do
        post :create, params: { group_id: group.id, event_id: course.id, id: invitation.id }
      end.to change(invitation, :declined_at).from(nil))
        .and.change(invitation, :status).to(:declined)
```

See:
- https://relishapp.com/rspec/rspec-expectations/v/3-5/docs/compound-expectations
- https://relishapp.com/rspec/rspec-expectations/v/3-5/docs/composing-matchers#composing-matchers-with-%60change%60

2021-09-29 10:17 UTC, TheWalkingLeek commented on app/abilities/ability_dsl/constraints/event.rb
> +    end
Das ist noch drin weeeeil...
Ich das Annehmen erst noch fälschlicherweise auf `POST .../:event_id/roles` gemacht habe. Das ist entsprechend nicht wirklich ein Use Case sondern einfach ein überbleibsel einer falsch gedachten Implementation.
Ob wir das jetzt drin lassen weiss ich jetzt nicht so ganz. An sich ist es ja jetzt toter Code und ich weiss nicht ob das effektiv Sinn macht das hier zu lassen. Fühlt sich irgendwie an wie bloat. Zumal es ziemlich schnell neu geschrieben wäre

2021-09-29 10:20 UTC, TheWalkingLeek commented on app/controllers/event/invitations_controller.rb
> +  end
Glaube schon. Problem war, dass nach dem Erstellen direkt zur show route redirected wurde. In diesem Fall gibt es diese aber nicht.

2021-09-29 12:14 UTC, kronn commented on app/controllers/event/invitations_controller.rb
> +  end
Ah, siehste. Ich habe also das `s` übersehen, dass es zur Index-Seite macht. :+1:

2021-09-29 12:16 UTC, kronn approved these changes

2021-09-29 13:51 UTC, merged