Add after_update hook to recalculate invoice after change
hitobito/hitobito pull request #1928
Opened 2022-11-29 06:49 UTC by TheWalkingLeek

Fixes: #1885

2022-11-29 10:18 UTC, kronn requested changes
Hmm. Das habe ich schon besser gesehen.

2022-11-29 10:18 UTC, kronn commented on app/models/invoice_item.rb
> +  after_update :recalculate!, if: :saved_change_to_count_or_unit_cost?
ich würde gerne vermeiden, in einem `after_`-hook einen Record zu speichern. Das kann leicht zur Callback-Hölle werden.

Könnte man nicht die internen Daten des InvoiceItem in einem `before_update` aktualisieren und dann nur das Aktualisieren der Rechnung im `after_udpate` anstossen, sofern nötig?

2022-11-29 10:18 UTC, kronn commented on spec/models/invoice_item_spec.rb
> +  end
Das ist ein Duplikat. :-)

Dafür fehlt mir noch eine Spec für den Change bei der Anzahl und eine, wenn sich der Name ändert, aber daher die Rechnung nicht neu berechnet wird.

2022-12-01 12:17 UTC, TheWalkingLeek commented on spec/models/invoice_item_spec.rb
> +  end
Der mit der Anzahl ist obendran. Daher auch kein Duplikat :P 
Ist einfach ähnlich daher bizli Verwechslungsgefahr. Negativfall fehlt aber wirklich und kommt... sofort! :)

2022-12-02 14:06 UTC, kronn approved these changes

2022-12-02 14:06 UTC, kronn commented on spec/models/invoice_item_spec.rb
> +  end
Whoops. Ähh, ich meine... (Mist) das war nur ein Test? :grin: 

Merci für die eine Spec, die wirklich noch gefehlt hat. :kissing_heart:

2022-12-05 06:20 UTC, merged