add icon after highlighting label in search result
hitobito/hitobito pull request #2222
Opened 2023-10-16 11:34 UTC by njaeggi

fixes #2060

2023-10-18 04:51 UTC, mtnstar commented
![image](https://github.com/hitobito/hitobito/assets/655627/89035aec-77bc-492c-b619-3c835a272e73)

falls z.B. ein & im Namen der Person vorhanden ist, dann wird das Resultat mit ;amp dargestellt.

Bitte diese Cases auch noch abdecken. Sicherstellen das es zu keiner SQL Injection führen kann.

2023-10-18 05:05 UTC, mtnstar requested changes
goooood :partying_face: 

see comments, some things to check.

maybe add a feature spec?

2023-10-18 05:05 UTC, mtnstar commented on app/javascript/javascripts/modules/remote_typeahead.js.coffee
> +    '<i class="fa fa-' + item.icon + '"></i> ' + label
habe noch kurz versucht dem namen einer person z.b. `;alert(1);` als Vornamen zu geben.
das hatte nicht zu einer Injection geführt.
ich sehe aber auch gerade nicht warum das hier sauber escaped wird. vielleicht nochmals drüber schauen ob man hier wirklich keinen code injecten kann.

2023-10-19 06:33 UTC, njaeggi commented
> falls z.B. ein & im Namen der Person vorhanden ist, dann wird das Resultat mit ;amp dargestellt.

Dieser Bug ist ein Problem vom Backend und nicht Frontend und hat nichts mit dem eigentlich gemeldeten Bug zu tun, @ThomasEllenberger meinte ich soll einfach sobald diese PR gemerged wird, im Ticket einen kurzen Kommentar schreiben

2023-10-30 06:42 UTC, mtnstar commented
> > falls z.B. ein & im Namen der Person vorhanden ist, dann wird das Resultat mit ;amp dargestellt.
> 
> Dieser Bug ist ein Problem vom Backend und nicht Frontend und hat nichts mit dem eigentlich gemeldeten Bug zu tun, @ThomasEllenberger meinte ich soll einfach sobald diese PR gemerged wird, im Ticket einen kurzen Kommentar schreiben

kannst du dafür einfach ein follow-up ticket eröffnen? ein kommentar verstaubt dann noch mehr :wink:

2023-10-30 07:35 UTC, merged