JsonApi: define contact accounts sideloads on GroupResource
hitobito/hitobito pull request #2554
Opened 2024-04-08 16:19 UTC by daniel-illi

fixes #2537

2024-04-15 08:02 UTC, mtnstar requested changes
looks pretty good ... some comments to check ...

2024-04-15 08:51 UTC, mtnstar commented
I think there's also a newer graphiti release ... does it make sense to upgrade it together with this PR?

2024-04-15 09:00 UTC, daniel-illi commented on app/abilities/json_api/contact_account_ability.rb
`Contactable` is e.g. `Person` or `Group`. 
`contact_account` is the opposite of the relation, one of `PhoneNumber`, `SocialAccount`, or `AdditionalEmail`

2024-04-19 11:43 UTC, daniel-illi commented on app/abilities/group_details_readables.rb
> +        "#{Group.quoted_table_name}.lft >= ? AND #{Group.quoted_table_name}.rgt <= ? ",
:+1:

2024-04-19 13:58 UTC, daniel-illi commented on app/abilities/group_details_readables.rb
> +        "#{Group.quoted_table_name}.lft >= ? AND #{Group.quoted_table_name}.rgt <= ? ",
I agree, but this is not an AREL statement but a custom `OrCondition` statement which does not support named arguments.

2024-04-19 15:18 UTC, merged