create folder for each module and add common module
hitobito/hitobito pull request #2630
Opened 2024-05-27 10:02 UTC by MarcEgliP

2024-06-03 05:43 UTC, mtnstar requested changes
going into the right direction ... but we can improve that even more !

2024-06-03 05:43 UTC, mtnstar commented on doc/developer/01_getting_started.md
> +| Task                      | Beschreibung                                                                                           |
can you extract this table to a separate file?
does it make sense to ask a new developer to just randomly check those commands?

2024-06-03 05:43 UTC, mtnstar commented on doc/developer/01_getting_started.md
> +- [ ] Look at the Github Board: [Github Project](https://github.com/orgs/hitobito/projects/14)
this is not public ... so don't add this link here
I think you can remove this whole Stage 3 section

2024-06-03 05:43 UTC, mtnstar commented on doc/developer/README.md
> +  * [In general](modules/common/common.md)
```suggestion
  * [In general](modules/common/README.md)
```
maybe use parent title here that always points to README.md ... in this case: modules/common/README.md

2024-06-03 05:43 UTC, mtnstar commented on doc/developer/modules/common/interfaces/interfaces.md
> +# Schnittstellen
rename: common/api_auth/README.md

2024-06-03 05:43 UTC, mtnstar commented on doc/developer/01_getting_started.md
> +
create a getting started tutorial ... 
for example how to customize a function in a wagon

2024-06-03 12:14 UTC, njaeggi reviewed
Overall a lot of links to README files do not seem to work, probably because the path just says README not README.md

One example is the link from common/README.md to for example api_auth/README

This seems to be an issue for many links tho...

---
Also, why don't we change the whole documentation to english, I know some part of the documentation is already there in german, but just mixing it into freshly added  english parts makes it even more confusing in my opinion. :dizzy_face:

2024-06-03 12:15 UTC, njaeggi commented on doc/developer/09_rake_tasks.md
> +| `rake hitobito:abilities` | Alle Abilities ausgeben.                                                                               |
I noticed that a lot of other parts are german too, I summarized my thoughts in my comment :rocket:

2024-06-05 09:02 UTC, rnestler commented on doc/developer/getting_started.md
> +- [ ] Make sure Tests 👨‍🔬 are running, look at [Tests](02_testing.md)
Link is broken.

2024-06-05 09:02 UTC, rnestler commented on doc/developer/getting_started.md
> +- [ ] Read and understand the [guidelines](03_guidelines.md) 📜 of Hitobito
Link is broken.

2024-06-05 09:05 UTC, rnestler commented on doc/developer/guidelines.md
> +..) siehe [doc/architectur/08_kozepte.md](modules/common/architecture/08_konzepte.md).
Link broken

2024-07-12 12:22 UTC, codez reviewed
Bitte auch noch die Commits passend stashen. Zig Commits mit der Message "Update documentation" bringen nichts. Vielleicht reicht ein einziger?

2024-07-12 12:22 UTC, codez commented on doc/developer/common/api/json_api.md
> -
Diese Datei wird in der Applikation unter /api angezeigt. Daher muss der Link auf die Swagger Doku dort irgendwie mit rein, idealerweise noch viel prominenter als jetzt irgendwo mitten im Dokument. Bis eine andere Lösung umgesetzt ist, würde ich diesen Link hier belassen, da diese Datei wohl viel häufiger in der Applikation als auf Github angeschaut wird.

2024-07-12 12:22 UTC, codez commented on doc/developer/common/api/service_accounts.md
> +Service accounts allow to create a dedicated account with certain permissions for an external application. Using this account, the external application can then access the [JSON API](modules/common/a
Stimmt der Link? `/modules` gibt's ja nicht mehr. Dasselbe mehrmals weiter unten.

2024-07-12 12:22 UTC, codez commented on doc/developer/common/gems/README.md
> +| NestedSet  | Manage and modify hierarchical data structures      | [Nested Set](nested_set/README.md)
Diese Datei könnte allenfalls mit architecture/techstack.md zusammengefasst werden.

2024-07-12 12:22 UTC, codez commented on doc/developer/common/gems/cancancan/README.md
> +
Vorerst reicht ja eine Datei pro Gem. Ich würde daher nicht pro Gem ein Ordner machen. 

Die Wagon Aspekte sind so zentral für Hitobito, die würde ich wohl nicht unter `gems` ablegen, sondern unter einem eigenen Ordner `common/wagons`.

2024-07-12 12:22 UTC, codez commented on doc/development/01_basics.md
> -#### Local installation
Dieser Abschnitt soll auch noch übernommen werden, da eine lokale Installation ebenfalls unterstützt wird.

2024-07-16 14:10 UTC, codez commented
@MarcEgliP Kannst du bitte noch die offenen Punkte von meinem Feedback angehen oder kommentieren, falls etwas dagegen spricht?

2024-09-12 08:14 UTC, codez approved these changes
Sieht gut aus, noch der letzte Feinschliff, dann kann das gemerged werden.

2024-09-12 08:14 UTC, codez commented on doc/architecture/gems/dry_crud.md
> +new controller.
Da würde ich eher aus der Perspektive von hitobito schreiben. Also z.B. 

dry_crud was used to generate several classes like the `CrudController` to generalize CRUD actions for our models.

2024-09-12 08:14 UTC, codez commented on doc/developer/getting_started.md
> +- [ ] Make sure Tests 👨‍🔬 are running
Link zur Testing Doku hinzufügen

2024-09-12 11:19 UTC, merged