Feature/2622 household aside person view
hitobito/hitobito pull request #2661
Opened 2024-06-06 14:04 UTC by Largo

fixes #2622

2024-06-10 11:24 UTC, TheWalkingLeek requested changes

2024-06-10 11:24 UTC, TheWalkingLeek commented on app/components/household_aside_component.html.haml
> +          = render(HouseholdAsideMemberComponent.new(person:))
```suggestion
          = render(HouseholdAsideMemberComponent.new(person: person))
```
Sonst gibt das bei mir einen Syntaxerror

2024-06-10 11:24 UTC, TheWalkingLeek commented on app/components/household_aside_component.rb
> +    false
Laut ticket sollen die aber schon angezeigt werden.. :thinking:
Ist das so abgesprochen?

2024-06-10 11:24 UTC, TheWalkingLeek commented on app/components/household_aside_component.rb
> +    people_in_household?
Dann wird der "Erstellen" Button aber auch nicht angezeigt

2024-06-10 11:24 UTC, TheWalkingLeek commented on spec/components/household_aside_component_spec.rb
> +      allow(component).to receive(:show_buttons?).and_return(true)
Ich fänds besser hier jeweils ein Szenario zu bauen welches zu dem entsprechenden return value führt statt diesen einfach zu mocken.
Aktuell testen wir die Logik von `#show_component?` `#people_in_household?` und `show_buttons?` gar nicht

2024-06-10 11:24 UTC, TheWalkingLeek commented on app/components/household_aside_member_component.rb
> +    link_to_if(link_person?, member.full_name, member, data: { turbo_frame: '_top' })
:+1:

2024-06-10 11:39 UTC, Largo commented on app/components/household_aside_component.rb
> +    false
Die dahinterstehende logik gibts noch nicht im core. das sei ein anderes ticket.

2024-06-10 11:42 UTC, Largo commented on app/components/household_aside_component.html.haml
> +          = render(HouseholdAsideMemberComponent.new(person:))
Überraschend. Ist eigentlich ein Ruby 3 Feature.

2024-06-11 11:52 UTC, Largo commented on app/components/household_aside_component.rb
> +    false
ist nun so geloest dases im produktion nicht angezeigt wird

2024-06-11 11:52 UTC, Largo commented on spec/components/household_aside_component_spec.rb
> +      allow(component).to receive(:show_buttons?).and_return(true)
verstanden. ist umgebaut :)

2024-06-12 07:11 UTC, amaierhofer requested changes
Wenn ViewComponent dann bitte best practices verfolgen. Rebase und links noch noch auf den `HouseholdsController` anpassen. Eventuell sollte das schon auch in Produktion rendern, damit das der SAC auch zu gesicht bekommt.

2024-06-12 07:11 UTC, amaierhofer commented on spec/components/household_aside_component_spec.rb
> +  def create_household(people)
Bitte Households::SpecHelper inkludieren und die dort definierte create_household method verwenden

2024-06-12 11:40 UTC, Largo commented on app/components/household_aside_component.rb
> +    I18n.t("#{I18N_PREFIX}.#{key}")
man koennte die translations in einem separaten yaml file neben dem componenten ablegen. das meinst du oder? Aber das gaebe dann Aufwand mit dem Uebersetzungssystem. 
Oder meinst du etwas anderes.

2024-06-12 11:58 UTC, Largo commented on spec/components/household_aside_component_spec.rb
> +  let(:helpers) do
Ich habe experimentiert und im spec_helper den devise helper testweise eingebaut, aber can? zu mocken scheint sinnvoller.

2024-06-12 12:24 UTC, daniel-illi commented on app/components/household_aside_component.rb
> +    return false if Rails.env.production?
@Largo ich denke da haben wir irgendwo ein Missverständnis. Die component sollte auf production doch schon angezeigt werden.

2024-06-12 12:42 UTC, Largo commented on app/components/household_aside_component.rb
> +    return false if Rails.env.production?
@daniel-illi ja, vorallem jetzt wo der household controller da ist.

2024-06-12 12:51 UTC, Largo commented on spec/components/household_aside_component_spec.rb
> +  def create_household(people)
machen wir das doch nachdem der branch mit dem spechelper gemergt ist.

2024-06-12 12:51 UTC, Largo commented on spec/regressions/people_controller_spec.rb
> +  def create_household(people)
machen wir das doch nachdem der branch mit dem spechelper gemergt ist.

2024-06-12 14:47 UTC, merged