Fix charlock_holmes build on newer systems
hitobito/hitobito pull request #2675
Opened 2024-06-10 16:24 UTC by rnestler

On my system charlock_holmes fails to build, since it overrides C++ compiler flags.

2024-06-10 17:48 UTC, kronn requested changes
I somehow want to have your fix, but distributed as a gem. Do you have expectations when it might be merged?

Alternatively, could you create a local workaround to fix your setup?

At the very least, I would like to see a comment which PR and issue forced us to have a git dependency for this.

2024-06-11 11:34 UTC, rnestler commented
> Alternatively, could you create a local workaround to fix your setup?

Sadly not yet. I think a local workaround would be possible with the latest master which has https://github.com/brianmario/charlock_holmes/pull/153 merged.

2024-06-11 11:38 UTC, rnestler commented
Hah I found one: `gem install charlock_holmes -- --with-cxxflags='#'` this will comment out the custom cxxflags of the package. Feels like a shell injection  :laughing:

2024-06-11 14:52 UTC, rnestler commented
Since I found a workaround I guess we can close this.

2024-06-11 14:52 UTC, closed without merging

2024-06-11 17:14 UTC, kronn commented
> Hah I found one: `gem install charlock_holmes -- --with-cxxflags='#'` this will comment out the custom cxxflags of the package. Feels like a shell injection  :laughing: 

I guess technically, it is.

I can't help but think "little Bobby Cflags, we call him..." https://xkcd.com/327/ :joy: