[WIP] feature/hitobito_youth#58
hitobito/hitobito pull request #2769
Opened 2024-08-13 14:00 UTC by diegosteiner

2024-08-16 14:22 UTC, diegosteiner commented on app/domain/ahv_number_validator.rb
> +class AhvNumberValidator < ActiveModel::EachValidator
Extrahiert aus hitobito_youth/app/models/youth/person.rb

2024-08-16 14:22 UTC, diegosteiner commented on app/models/event/answer.rb
> +  attribute :answer, :json
Das Problem, das hiermit gelöst wird ist folgendes: 

In der bisherigen Implementation wurde die serialization der Antwort unmittelbar beim aufrufen des Setters gemacht. Da dieses Verhalten nun abhängig vom `type` der `Event::Question` ist, ist das nicht mehr möglich.

Der Setter wird unter Umständen vor dem setter der Question aufgerufen, deshalb muss das zu einem späteren Zeitpunkt gemacht werden. Ich habe hierfür `before_validation` gewählt.

Jetzt ists aber so, dass der Default setter für Strings den Array, welcher hier bei Mehrfachantworten übergeben wird, einfach mit `to_s` serialisiert, was später, z.B. in der `before_validation` nicht mehr einfach deserialisiert werden kann.

Mit diesem `attribute :answer, :json` können die Daten aber leicht wieder ausgelesen und weiterverarbeitet werden. 

Hat das zusätzliche Konsequenzen, an welche ich nicht gedacht habe?

2024-08-16 14:22 UTC, diegosteiner commented on app/models/event/question.rb
> +  # TODO: move choices
`choices` ist eigentlich nur ein Attribut von Event::Question::Default. Es führt aber zu *missing translations*, wenn man das direkt dahin verschiebt.

Vorschläge?

2024-08-16 14:22 UTC, diegosteiner commented on app/models/event/question.rb
> +
Ich habe das hierhin extrahiert, weil es ab sofort an mehreren Orten verwendet wird (hitobito_youth und hitobito_jubla)

2024-08-16 14:22 UTC, diegosteiner commented on app/models/event/question/default.rb
> +class Event::Question::Default < Event::Question
Extrahiert aus hitobito/app/models/event/question.rb

2024-08-16 14:22 UTC, diegosteiner commented on app/models/event/question/default.rb
> +    return unless with_choices? && with_checkboxes? && answer.answer.is_a?(Array)
Der Aufruf `answer.answer.is_a?(Array)` würde fehlschlagen, wenn der Text nicht z.B. als JSON serialisiert wird

2024-08-16 14:22 UTC, diegosteiner commented on app/models/event/answer.rb
> +  attribute :answer, :json
Allenfalls bei bestehenden Antworten?!

2024-08-22 14:44 UTC, diegosteiner commented on app/models/event/question/ahv_number.rb
> +class Event::Question::AhvNumber < Event::Question
Soll dieser Question-Type besser in den youth_wagon?

2024-08-29 09:44 UTC, kronn requested changes
Insgesamt gefällt mir das gut. Ich habe noch ein paar Rückfragen als Kommentare hinuzgefügt

2024-09-03 09:09 UTC, diegosteiner commented on db/migrate/20240812095000_add_derived_from_to_event_questions.rb
> +    # Event::Question.where(event: nil).find_each(&:derive_for_existing_events)
Ja das ist noch die Frage... @ThomasEllenberger meint, dass das im Nachfolgeissue [hitobito_youth#59](https://github.com/hitobito/hitobito_youth/issues/59) gemacht werden soll. Ich möchte hier aber noch auf eine Feinheit hinweisen; Von mir aus gesehen sind das zwei einzelne Schritte:

- AHVnNummer von Person auf alle Events übertragen: das muss sicher im Nachfolgeissue abgehandelt werden.
- Frage mit der AHV-Nummer auf bestehende Events hinzufügen: die Migration hier würde nur diesen Punkt angehen. Aus meiner Sicht könnte/sollte das schon gemacht werden, damit es keine Inkonsistenz zwischen Anlässen die **kurz vor** der Migration angelegt wurde (= haben die Frage nicht drin) und Anlässen die **kurz nach** der Migration angelegt wurden (= haben die Frage drin, aber keine bestehenden Antworten)

@ThomasEllenberger Wie soll ich verfahren? Beides in der 2. Migration machen? Dann würde ich das im Issue noch ergänzen.

2024-09-04 12:29 UTC, diegosteiner commented on db/migrate/20240903131542_change_event_answers_to_json_type.rb
> +    # change_column :event_answers, :answer, 'json USING answer::json'
@kronn wie siehst du das: Ich habe versucht den Spaltentyp auf Datenbanklevel zu ändern, aber es führt aus meiner Sicht zu ganz komischem Verhalten. Wir brauchen das auch nicht unbedingt, es geht ja nur darum, dass Arraywerte nicht unmittelbar serialisiert werden. Behalten wir das so bei oder soll ich noch Zeit investieren um das versuchen zum laufen zu bringen?

2024-09-04 12:34 UTC, diegosteiner commented on app/models/event/question.rb
>    translates :question, :choices
Im Bezug auf https://github.com/hitobito/hitobito/pull/2769#discussion_r1732781477 @kronn : 

Ich habe es versucht, es ist aus meiner Sicht aber nicht wirklich möglich, Globalize und STI zu vereinbaren. Ich denke es ist ok nur die eine, übergeordnete `Event::Question::Translation`-Klasse zu haben, sodass die Translations auch nur in der `event_questions_translations`-Tabelle gespeichert werden. Die zusätzlichen Attribute (hier z.B. `choice` werden ja auch in der Parent-Tabelle `event_questions` gespeichert). 

Der Kommentar soll helfen, da in Zukunft nicht zu vergessen

2024-09-04 12:35 UTC, diegosteiner commented on app/models/event/answer.rb
> +  attribute :answer, :json
Im Bezug auf https://github.com/hitobito/hitobito/pull/2769#discussion_r1735662709 @kronn : 

Ich habe den Kommentar hier am sinnvollsten gefunden

2024-09-04 12:42 UTC, diegosteiner commented on db/migrate/20240812095000_add_derived_from_to_event_questions.rb
> +    # Event::Question.where(event: nil).find_each(&:derive_for_existing_events)
@ThomasEllenberger Da hast du völlig recht und es stimmt auch, dass die Events ungültig würden, wenn wir keinen Default-Wert setzen. Aber: Das ist ja auch ein bisschen der Witz an der Sache, dass sie diese Entscheidung für die Standardfragen treffen sollen. Tja... 

Aktuell ist es so, dass «neue» Fragen (welche seit dem Erstellen des Events als Standardfragen hinzugefügt wurden) beim klick auf «Bearbeiten» beim Event hinzugefügt werden, und damit die Events erst ungültig würden, sobald man auf Bearbeiten geht. Ich denke dieses Verhalten macht eigentlich auch hier Sinn.

Falls du einverstanden bist, würde ich die Migration noch bereinigen.

2024-09-04 14:12 UTC, diegosteiner commented
@kronn hier im core ist soweit alles fertig für ein Rereview!

2024-09-06 12:27 UTC, diegosteiner commented
@ThomasEllenberger ich würde mich bez. den Hilfetexten gerne noch mit einem Lead-Dev kurzschliessen. Die AHV-Nummer ist leider nicht einfach nur ein Attribut, sondern eben ja eine Frage auf einem Anlass und damit viel dynamischer. Mit der herkömmlichen HelpText implementation ist ein Hilfetext hier kaum möglich. Eher noch möglich wäre es, das mit einem `CustomContent` umzusetzen.

2024-09-09 14:21 UTC, ThomasEllenberger commented
Wie besprochen, lassen wir die Anforderung an den Hilfetext einmal weg, und setzen das Feature ohne um. Haben wir am Ende noch Budget werden wir diskutieren, ob wir es dafür einsetzen.

2024-09-12 12:54 UTC, merged