replace mysql with postgres in documentation and in sbom file generation
hitobito/hitobito pull request #2801
Opened 2024-09-02 07:03 UTC by MarcEgliP

2024-09-10 07:12 UTC, njaeggi commented on doc/development/04_wagons.md
> +]
Also document the search_strategies domain classes and add some documentation that PgSesarchable has to be included in the corresponding model

2024-09-25 08:11 UTC, njaeggi requested changes
Just one small change to documentation, the rest looks good to me :)

2024-09-25 08:11 UTC, njaeggi commented on doc/development/04_wagons.md
> +]
Please note that PGSearchable has to be initialzed again, also note that we have a search strategy for each class, for maybe special cases like person search but also for the basic searches to check min length for terms, we never use the model search scope directly, to improve performance.

2024-09-25 09:24 UTC, njaeggi requested changes

2024-09-25 09:24 UTC, njaeggi commented on doc/architecture/wagons/README.md
> +Dont forget to include de PgSearchable module too:
de?

2024-09-25 09:28 UTC, njaeggi requested changes

2024-09-25 09:28 UTC, njaeggi commented on doc/architecture/wagons/README.md
>  ### Make attributes searchable
This isn't really a wagon documentation, I would maybe move this somewhere else, and only explain how to add something to SEARCHABLE_ATTRS in wagons here :rocket:

2024-09-25 09:39 UTC, merged

2024-09-25 11:17 UTC, lkleisa commented
@MarcEgliP Nice work! 🚀