Update address of all household members on save
hitobito/hitobito pull request #2825
Opened 2024-09-06 11:41 UTC by hunchr

Fixes https://github.com/hitobito/hitobito_sac_cas/issues/908

2024-09-10 06:00 UTC, TheWalkingLeek requested changes
https://github.com/hitobito/hitobito/pull/2678/files#diff-7ad637eb3d0b388f39c623722da0dfe3b1d6779a0d70bb247159f4c38c17d03bL44
Hier ist das wohl rausgefallen. Find ich ehrlichgesagt besser in einem Controller-Hook statt jedes mal auf dem Model. Hab da persönlich schon die Erfahrung gemacht dass dann plötzlich auf dem Model zu viel passiert und Hooks an Orten ausgeführt werden wo es gar nicht gedacht war.

Zudem kannst du dann ja einfach `entry.household.save` callen. Statt das selber nochmal nachzubauen

2024-09-10 07:27 UTC, hunchr commented
> Zudem kannst du dann ja einfach `entry.household.save` callen. Statt das selber nochmal nachzubauen

wie meinst du? `save` ändert die addresse ja nicht

2024-09-10 11:38 UTC, hunchr commented
anscheinend ist der household invalid, weil `"Mindestens eine Person in der Familie muss bereits SAC Mitglied sein."`. deshalb werden die adressen nicht aktualisiert. wenn ich versuche, ein mitglied zu der familie hinzuzufügen, bekomme ich den error:

```txt
NoMethodError (undefined method `group' for nil:NilClass):
  
app/models/household.rb:149:in `block in save_records'
app/models/household.rb:145:in `save_records'
app/models/household.rb:62:in `save'
app/controllers/households_controller.rb:30:in `update'
app/controllers/application_controller.rb:81:in `store_current_person'
app/controllers/concerns/localizable.rb:25:in `set_locale'
```

2024-09-12 04:46 UTC, TheWalkingLeek requested changes
Ich habs jetzt mittels `entry.household.save! if entry.household_key.present?` getestet und bin auf keine Probleme gestossen :thinking: 
Hattest du das `if entry.household_key.present?` auch drin? Weil sonst fliegt er natürlich aufs Maul

2024-09-12 06:33 UTC, hunchr commented
@TheWalkingLeek bei mir geht das nicht
<img width="740" alt="image" src="https://github.com/user-attachments/assets/45d0c387-4050-42de-9d00-75ab358b08d8">

willst du es fixen?

2024-09-13 07:24 UTC, TheWalkingLeek approved these changes

2024-09-13 07:24 UTC, merged