Bug/hitobito#2845
hitobito/hitobito pull request #2860
Opened 2024-09-18 15:04 UTC by Largo

2024-09-19 15:06 UTC, codez requested changes
Jetzt wo die [Definition of Done](https://github.com/hitobito/hitobito/blob/master/doc/developer/process/definition_of_done.md) im Git ist: Kannst du bitte die Commit squashen, bevor du den Pull Request zum Review übergibst? 

Im CustomContent#body_with_values sollte das `html_safe` noch entfernt werden oder nur auf dem `body` aufgerufen werden. Falls Placeholders mal nicht via `values_for_placeholders` erstellt werden und nicht escaped werden, gibt es dort sonst noch immer eine Lücke.

2024-09-23 10:07 UTC, Largo commented
> Jetzt wo die [Definition of Done](https://github.com/hitobito/hitobito/blob/master/doc/developer/process/definition_of_done.md) im Git ist: Kannst du bitte die Commit squashen, bevor du den Pull Request zum Review übergibst?
> 
> Im CustomContent#body_with_values sollte das `html_safe` noch entfernt werden oder nur auf dem `body` aufgerufen werden. Falls Placeholders mal nicht via `values_for_placeholders` erstellt werden und nicht escaped werden, gibt es dort sonst noch immer eine Lücke. Idealerweise werden die Placeholder sogar erst in `body_with_values` escaped, und nicht bereits in `values_for_placeholders`.

Re: html_safe body: 
Ein grosses Problem hier ist, das Methoden wie gsub und gsub! den SafeBuffer zerstoeren => d.h. es bringt nichts den body html_safe zu markieren, weil man spaeter mit gsub! die Platzhalter austauscht. Der ganze String ist dann wieder ein regulaerer unsafe String, wo die unsicheren Teile nicht markiert sind. Zu viel eigenen Code möchte ich auf diesem Level nicht hereinbringen. Ich arbeite mich da jetzt noch drumherum.

2024-09-23 14:33 UTC, closed without merging

2024-09-23 14:37 UTC, Largo commented
changed branch

2024-09-23 14:37 UTC, Largo commented
changed branch