Bug/901/dependent checkbox
hitobito/hitobito pull request #2865
Opened 2024-09-19 11:42 UTC by njaeggi

2024-09-23 06:55 UTC, TheWalkingLeek approved these changes

2024-10-11 10:37 UTC, amaierhofer requested changes

2024-10-11 10:37 UTC, amaierhofer commented on app/javascript/controllers/form_field_check_dependent_controller.js
> +  static targets = ["checkbox"]
Ich finde die depdent checkboxes sollten auch noch als targets definiert sein. Vielleicht 

`static targets = ["main", "dependent"]` damit die abgrenzung zwischen den 2 klarer wird und wir die `querySelectorAll` loswerden

und ich finde `toggleMain` und `toggleDependent` besser als (toggle imho spezifischere UI controll sprache, und main besser als master)

2024-10-11 10:39 UTC, amaierhofer requested changes

2024-10-11 10:39 UTC, amaierhofer commented on app/javascript/controllers/form_field_check_dependent_controller.js
> +      this.checkboxTarget.checked = false;
Ich verstehe die Anforderung so, dass es nur checken und nicht unchecken soll

2024-10-15 13:42 UTC, merged