PEOPLE: Duplicate Finder Memory Usage (#2824)
hitobito/hitobito pull request #2893
Opened 2024-09-30 15:21 UTC by Largo

- rename duplicate to unique
- use duplicate_ids and don't create an array with all the data of a person everytime.

2024-10-16 14:26 UTC, amaierhofer requested changes
Das Memory Problem wird dadurch nicht behoben, da weiterhin für jede Person ein Eintrag in `unique_entries` existiert. Zudem find ich das naming `handle_single_duplicate` und `handle_multiple_duplicates` verwirrend, besonders wenn die Klasse vom `People::DuplicateLocator` verwendet wird. 

Wahrscheinlich  macht es Sinn, die Klasse aufzuteilen. Ein PORO für die Query der die ids der für die  Attribute gefunden Personen liefert und einen Count/Errors Teil der anhand von den ids die count und errors für den `Import::PersonImport` aufbereitet.

2024-10-21 10:48 UTC, Largo commented
Hier erstmal noch eine kleine Messung zu den Allocations vor der Anpassung: Innerhalb vom person_duplicate_finder_spec:
`context "multiple updates to the same person" do
    let(:existing) { Person.create!(attrs.merge(first_name: "foo")) }
    let(:attrs) { {email: "foo@bar.com"} }

    before do
      existing
      @first = finder.find(attrs)
    end

    it { is_expected.to be @first }

    it "allocations" do
      expect(finder.allocations { @second = finder.find(attrs) }).to eq(190)
    end
  end`

=> 237 vor Anpassung, 190 nach Anpassung

2024-10-22 01:17 UTC, Largo commented
Allokationen finden:



```
require 'allocation_tracer'
require 'pp'


attrs = {
  first_name: "John",
  last_name: "Doe",
  company_name: "Acme Corp",
  zip_code: "12345",
  birthday: "1990-01-01",
  email: "john.doe@example.com"
}

result = ObjectSpace::AllocationTracer.trace do
  finder = Import::PersonDuplicateFinder.new
  1000.times do |i|
    current_attrs = attrs.merge(
      first_name: "John#{i % 10}",
      email: "john#{i}@example.com"
    )
    finder.find(current_attrs)
  end
end

p result
```

 ["/home/andi/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7.8/lib/active_record/sanitization.rb",
  157]=>[22000, 0, 9394, 0, 1, 1714512],
...
 ["/home/andi/workspace/hitobito/app/hitobito/app/domain/import/person_duplicate_finder.rb", 100]=>
  [1000, 0, 427, 0, 1, 136320],

2024-10-22 01:59 UTC, Largo commented
> Das Memory Problem wird dadurch nicht behoben, da weiterhin für jede Person ein Eintrag in `unique_entries` existiert. Zudem find ich das naming `handle_single_duplicate` und `handle_multiple_duplicates` verwirrend, besonders wenn die Klasse vom `People::DuplicateLocator` verwendet wird.
> 
> Wahrscheinlich macht es Sinn, die Klasse aufzuteilen. Ein PORO für die Query der die ids der für die Attribute gefunden Personen liefert und einen Count/Errors Teil der anhand von den ids die count und errors für den `Import::PersonImport` aufbereitet.

So wie ich das sehe hat unique_entries hat normalerweise nur eine person drin. Das wird als eine Art cache gebraucht.
Meine Anpassung bringt das es weniger allokationen gibt beim SQL Query erstellen. Ich habe soweit Moeglich die Allokationen reduziert. An der Klasse lohnt sich nicht mehr viel zu machen. Am besten wäre, dass anstatt vielen Jobs nur ein Job durchläuft mit weniger SQL Queries. Das lässt sich aber nicht so einfach machen. Am besten besprechen wir dies.

2024-10-24 12:32 UTC, Largo commented
passt, danke fuers erweitern

2024-10-25 07:03 UTC, merged