Hitobito sww#28
hitobito/hitobito pull request #2975
Opened 2024-11-04 13:37 UTC by diegosteiner

implements [hitobito_sww#28](https://github.com/hitobito/hitobito_sww/issues/28)

2024-11-04 13:46 UTC, diegosteiner commented on app/javascript/javascripts/modules/invoice_message_template.js.coffee
> +$(document).on('change', '#invoice_message_template_id', (event) ->
Ich habe jetzt hier absichtlich jQuery verwendet, um es gleich zu machen wie im Rest des Projektes.

2024-11-04 13:46 UTC, diegosteiner commented on app/models/message_template.rb
> +class MessageTemplate < ApplicationRecord
Ich bin nicht ganz sicher, ob der in der Tech-Spec vorgeschlagene Name wirklich passend ist. Soll das Template allgemein verwendet werden oder nur für die Rechnungen? Falls 2.) würde ich vorschlagen, das noch auf `InvoiceTextTemplate` o.Ä. umzubenennen.

2024-11-04 13:46 UTC, diegosteiner commented on app/models/message_template.rb
> +  belongs_to :templated, polymorphic: true
Hier habe ich nicht eine Relation wie vorgeschlagen zum Layer gemacht, sondern gehe über die InvoiceConfig. Ich persönlich finde das klarer, wenn man das noch auftrennen muss wirds komplizierter, denke ich. @ThomasEllenberger  was meinst du?

2024-11-07 09:08 UTC, TheWalkingLeek requested changes
Schaut gut aus!
Ich hab noch einen Kommentar im Wagon PR hinterlegt. Wenn du zusätzlich das JS File umschreiben könntest, alle Lizenz-headers noch einfügst und vielleicht eine kurze Doku wo das MessageTemplate Model beschrieben ist im `doc/developer/invoices/` ablegen könntest wäre super :)
Manuell getestet habe ich auch und funktioniert as far as i can tell bestens

2024-11-12 13:08 UTC, TheWalkingLeek approved these changes

2024-11-25 15:54 UTC, merged