feature/rails-update-7.1
hitobito/hitobito pull request #3014
Opened 2024-11-20 10:29 UTC by MarcEgliP

2024-12-19 10:40 UTC, codez approved these changes
Noch einige kleine Anpassungen, sonst sieht es aber gut aus :+1:

2024-12-19 10:40 UTC, codez commented on app/controllers/households_controller.rb
> +      render :edit, status: :unprocessable_CON
Das ist nicht so gedacht, oder ich verstehe es nicht :thinking:

2024-12-19 10:40 UTC, codez commented on app/helpers/sheet/group/nav_left.rb
> +        li_tag.html_safe
:boom: Das ist nicht safe, zB. wenn css_classes `['dummy" onclick="alert('pwnd')" alt="unsafe']` ist. Da muss zwinged wieder ein sanitize hin.

2024-12-19 10:40 UTC, codez commented on config/environments/production.rb
> +  config.enable_reloading = true
Production sollte reloading nicht enabled haben

2024-12-19 10:40 UTC, codez commented on config/environments/test.rb
> -  # Set to false for faster wagon tests once db is setup
Der Kommentar war doch hilfreich, oder nicht?

2024-12-19 10:40 UTC, codez commented on config/initializers/new_framework_defaults.rb
>  Rails.application.config.active_record.belongs_to_required_by_default = false
Dieses File ist eigentlich nur für Upgrade Zwecke gedacht. Wenn die Konfiguration so bleibt, kann sie ins config/application.rb übernommen werden.

2024-12-19 12:18 UTC, kronn requested changes
Gute Arbeit insgesamt. Ich habe noch ein paar Anmerkungen...

2024-12-19 12:18 UTC, kronn commented on app/models/concerns/i18n_enums.rb
> +        rescue I18n::MissingTranslationData
Tritt dies auch in Production so auf? Ich gehe davon aus, dass wir nur in dev und test bei missing translations raisen.

2024-12-20 07:47 UTC, codez commented
Noch zwei Fragen:
- Hast du den Server mal lokal mit RAILS_ENV=production gestartet und durchgeklickt? Dabei kommen teilweise noch prod-spezifische Konfigurationen bzw Probleme damit zum Vorschein.
- Gibt es schon einen Folgetask, um auch noch die übrigen Gems zu aktualisieren, insbesondere auch diejenigen, welche im Gemfile eine Versions Constraint definiert haben?

2025-02-04 08:58 UTC, kronn requested changes
Noch ein paar weitere Anmerkungen, wir sind aber schon auf einem guten Weg.

2025-02-04 08:58 UTC, kronn commented on app/domain/mailing_lists/subscribers.rb
> +    conditions = group_subscriptions[:role_type].not_eq(nil).then { |scope| event_subscriptions? ? scope.or(event_subscriptions[:person_id].not_eq(nil)) : scope }.then { |scope| including_people_subs
Hier könnte die Lesbarkeit von ein paar Zeilenumbrüchen profitieren, finde ich. Man könnte zum Beispiel von jedem `.then` einen Zeilenumbruch machen...

```suggestion
    conditions = group_subscriptions[:role_type].not_eq(nil)
      .then { |scope| event_subscriptions? ? scope.or(event_subscriptions[:person_id].not_eq(nil)) : scope }
      .then { |scope| including_people_subscriptions? ? scope.or(including_person_subscriptions[:subscriber_id].not_eq(nil)) : scope }
      .then { |scope| excluding_people_subscriptions? ? scope.and(excluding_person_subscriptions[:subscriber_id].eq(nil)) : scope }
      .then do |scope|
```

Wenn RuboCop da noch mehr oder weniger whitespace vorne möchte, ist das natürlich auch noch okay.

2025-02-04 08:58 UTC, kronn commented on app/domain/mailing_lists/subscribers.rb
> +    sql = <<~SQL.split.join(" ")
```suggestion
    sql = <<~SQL.squish
```

https://devdocs.io/rails~7.1/string#method-i-squish löst das allgemeiner.

2025-02-04 08:58 UTC, kronn commented on app/domain/mailing_lists/subscribers.rb
> +      sql += <<~SQL.split.join(" ")
```suggestion
      sql += <<~SQL.squish
```

2025-02-04 08:58 UTC, kronn commented on app/domain/mailing_lists/subscribers.rb
> +      scope.and(group_subscriptions[:tag_id].eq(nil)
```suggestion
      next scope unless group_subscription_tags?
      
      scope.and(group_subscriptions[:tag_id].eq(nil)
```

RuboCop sollte hier eigentlich eine Leerzeile verlangen...

2025-02-04 08:58 UTC, kronn commented on bin/webpack-test-compile
>  cp -rf public/packs public/packs-test && echo "copied public/packs -> public/packs-test"
Wie abgesprochen:
entweder im dev compile aufrufen und kopieren
oder in test compile aufrufen und nicht kopieren

Wenn es funktioniert, ist die zweite Variante besser. Aber das muss getestet werden.

2025-02-04 08:58 UTC, kronn commented on db/seeds/support/location_seeder.rb
> +  SEED_MARKER = "locations seeded"
Wird der noch irgendwo verwendet? Ich dachte, dass das eher nur intern verwendet wird. Und mit den Anpassungen in diesem Branch sollten eher auch die externen Refrenzen auf diese Konstante entfernt werden. Dachte ich. 

Übersehe ich einen Use-Case?

2025-02-14 21:03 UTC, kronn approved these changes

2025-02-18 08:07 UTC, amaierhofer requested changes
Bitte noch app/domain/mailing_lists/subscribers.rb additions prüfen

2025-02-18 08:27 UTC, merged