Upgrade ruby to 3.2.6
hitobito/hitobito pull request #3106
Opened 2024-12-23 14:13 UTC by rnestler

2024-12-23 18:12 UTC, kronn requested changes
The Dockerfile also has the ruby-version and is arguably the most important of these files. 😊

2024-12-24 09:38 UTC, rnestler commented
> The Dockerfile also has the ruby-version and is arguably the most important of these files. 😊

I like my security fixes locally, who cares about production 😂 

Somehow I didn't see it while grepping for the old version...

Merry Christmas 😊 🎄

2024-12-26 10:30 UTC, rnestler commented
@kronn 

> The Dockerfile also has the ruby-version and is arguably the most important of these files. 😊

The version there is set to `3.2`, that means it always uses the latest available 3.2 version I assume?

2024-12-27 00:12 UTC, kronn approved these changes
This brings the dev-setup closer to the actually used version.

2024-12-27 00:13 UTC, merged